# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='album_art',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
