# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170814_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='listen_link',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='spotify_id',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='album_art',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
